# Generated by Django 4.0.2 on 2022-03-26 17:12

import apps.iranian_cities.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        ('iranian_cities', '0004_remove_abadi_shhahr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='spouse',
            name='birthdate_city',
            field=apps.iranian_cities.fields.ShahrestanField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_birthdate_cities', to='iranian_cities.shahrestan'),
        ),
        migrations.AddField(
            model_name='spouse',
            name='birthdate_province',
            field=apps.iranian_cities.fields.OstanField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_birthdate_province', to='iranian_cities.ostan'),
        ),
        migrations.AddField(
            model_name='spouse',
            name='issue_place',
            field=apps.iranian_cities.fields.ShahrestanField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_issue_places', to='iranian_cities.shahrestan'),
        ),
        migrations.AddField(
            model_name='spouse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouses', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(related_name='roles', through='personnel.UserRole', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate_city',
            field=apps.iranian_cities.fields.ShahrestanField(on_delete=django.db.models.deletion.CASCADE, related_name='birthdate_cities', to='iranian_cities.shahrestan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate_province',
            field=apps.iranian_cities.fields.OstanField(on_delete=django.db.models.deletion.CASCADE, related_name='birthdate_province', to='iranian_cities.ostan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=apps.iranian_cities.fields.ShahrestanField(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='iranian_cities.shahrestan', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='issue_place',
            field=apps.iranian_cities.fields.ShahrestanField(on_delete=django.db.models.deletion.CASCADE, related_name='issue_places', to='iranian_cities.shahrestan'),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=apps.iranian_cities.fields.OstanField(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='iranian_cities.ostan', verbose_name='province'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='personnel.role', verbose_name='role'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='deletedemand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_demands', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='contractcomment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_comments', to='personnel.contract', verbose_name='contract'),
        ),
        migrations.AddField(
            model_name='contractcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='contract',
            name='insurance_city',
            field=apps.iranian_cities.fields.ShahrestanField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_insurance_cities', to='iranian_cities.shahrestan', verbose_name='insurance city'),
        ),
        migrations.AddField(
            model_name='contract',
            name='insurance_province',
            field=apps.iranian_cities.fields.OstanField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_insurance_provinces', to='iranian_cities.ostan', verbose_name='insurance province'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='child',
            name='birthdate_city',
            field=apps.iranian_cities.fields.ShahrestanField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_birthdate_cities', to='iranian_cities.shahrestan'),
        ),
        migrations.AddField(
            model_name='child',
            name='birthdate_province',
            field=apps.iranian_cities.fields.OstanField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_birthdate_province', to='iranian_cities.ostan'),
        ),
        migrations.AddField(
            model_name='child',
            name='issue_place',
            field=apps.iranian_cities.fields.ShahrestanField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_issue_places', to='iranian_cities.shahrestan'),
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='bank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to=settings.AUTH_USER_MODEL, verbose_name='bank'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
